// <auto-generated />
using System;
using Challenge_MOTTU.Connection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Challenge_MOTTU.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250928031115_CriarTabelasUsuarioBikeEPending")]
    partial class CriarTabelasUsuarioBikeEPending
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Challenge_MOTTU.Model.Bike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ANO");

                    b.Property<int>("Disponivel")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DISPONIVEL");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("MODELO");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("NVARCHAR2(7)")
                        .HasColumnName("PLACA");

                    b.HasKey("Id");

                    b.ToTable("BIKE", "RM554694");
                });

            modelBuilder.Entity("Challenge_MOTTU.Model.Pending", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BikeId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("BIKE_ID");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_FIM");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_INICIO");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("BikeId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PENDING", "RM554694");
                });

            modelBuilder.Entity("Challenge_MOTTU.Model.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("SENHA");

                    b.HasKey("Id");

                    b.ToTable("USUARIOS", "RM554694");
                });

            modelBuilder.Entity("Challenge_MOTTU.Model.Pending", b =>
                {
                    b.HasOne("Challenge_MOTTU.Model.Bike", "Bike")
                        .WithMany("Pendings")
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Challenge_MOTTU.Model.Usuario", "Usuario")
                        .WithMany("Pendings")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bike");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Challenge_MOTTU.Model.Bike", b =>
                {
                    b.Navigation("Pendings");
                });

            modelBuilder.Entity("Challenge_MOTTU.Model.Usuario", b =>
                {
                    b.Navigation("Pendings");
                });
#pragma warning restore 612, 618
        }
    }
}
