<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Challenge_MOTTU.ML</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML" Version="4.0.3" />
    <PackageReference Include="Microsoft.ML.AutoML" Version="0.22.3" />
    <PackageReference Include="Microsoft.ML.FastTree" Version="4.0.3" />
  </ItemGroup>

</Project>
